import os
import csv
import re
import pandas as pd
from pathlib import Path
import geopandas as gpd
from shapely.geometry import Point
import subprocess
import json
import re
import glob
import yaml


# Load configuration file
def load_config(config_path):
    with open(config_path, "r") as file:
        config = yaml.safe_load(file)
    return config

def list_folders_two_levels_deep(path):
    """
    List all folders that are two levels deep and start with 8 digits (in the format yyyymmdd).

    :param path: Path to the directory to list folders in.
    :return: List of folder paths that match the date format.
    """
    # Regular expression to match folder names starting with 8 digits (yyyyMMdd)
    date_regex = re.compile(r'^\d{4}')

    # List to hold all matching folder paths
    matching_folders = []

    try:
        # Iterate through the first level of directories
        for first_level_folder in os.listdir(path):
            first_level_folder_path = os.path.join(path, first_level_folder)
            if os.path.isdir(first_level_folder_path) and date_regex.match(first_level_folder):
                # Iterate through the second level of directories within the first-level folder
                for second_level_folder in os.listdir(first_level_folder_path):
                    second_level_folder_path = os.path.join(first_level_folder_path, second_level_folder)
                    #if os.path.isdir(second_level_folder_path) and date_regex.match(second_level_folder):
                    if os.path.isdir(second_level_folder_path):
                        matching_folders.append(second_level_folder_path + '/01_Images/' + second_level_folder + '/')
        return matching_folders
    except FileNotFoundError:
        print(f"Error: The path '{path}' does not exist.")
        return []
    

def list_orthomosaics(om_path, maptiles_path):
    om_dict = {}

    for filename in os.listdir(om_path):
        print(f'filename: {filename}')
        if filename.endswith("aligned.tif"):
            parts = filename.split('_')
            print(f'parts: {parts}')
            if len(parts) >= 4:  # Ensure enough parts for farm_field, sensor, date
                try:
                    date = parts[-2].split('.')[0] # Get date and remove .tif
                    sensor = parts[-2]
                    farm_field_parts = parts[:-2]
                    farm_field = "_".join(farm_field_parts)

                    # Check if maptiles have already been generated by checking for the existence of folder in maptiles_path
                    # The folder will be maptiles_path/farm_field/date
                    
                    # Check if maptiles exist for this orthomosaic
                    maptile_farmfield = os.path.join(maptiles_path, farm_field)
                    maptile_farmfield_exists = os.path.exists(maptile_farmfield)
                    maptile_path = os.path.join(maptiles_path, farm_field, date)
                    maptiles_exist = os.path.exists(maptile_path)
                    
                    # Skip if date for maptiles already exist or orthomosaic is not rgb or  farmfield folder does not exist 
                    if maptiles_exist or not sensor == 'rgb' or not maptile_farmfield_exists:
                        continue


                    if farm_field not in om_dict:
                        om_dict[farm_field] = {}

                    # Store the full filename or just the date part as value if preferred
                    om_dict[farm_field][date] = filename 
                    print(f'adding {filename} to dictionary')
                except IndexError:
                    print(f"Warning: Could not parse filename: {filename}. Skipping.")
                except ValueError:
                    print(f"Warning: Could not parse date from filename: {filename}. Skipping.")
            else:
                print(f"Warning: Filename {filename} does not have enough parts. Skipping.")
    
    return om_dict

    
def geotagged_folders(folders):
    valid_folders = []
    invalid_folders = []
    for folder in folders:
        output_path = os.path.join(folder, 'OUTPUT')
                    # Check if 'OUTPUT' folder exists

        # Check if 'OUTPUT' folder exists
        if os.path.isdir(output_path):
            # Check if there's any .pdf file in the 'OUTPUT' folder
            pdf_exists = any(file.lower().endswith('.pdf') for file in os.listdir(output_path) if os.path.isfile(os.path.join(output_path, file)))
            # Read the lines in the csv file and compare with the number of images
            csv_files = glob.glob(os.path.join(output_path, "*.csv"))
            csv_file = csv_files[0] if csv_files else None
            if csv_file is None:
                print(f"Skipping {folder}: No CSV file found in OUTPUT")
            #print(f'csv file = {csv_file}')

            """
            df_csv = pd.read_csv(csv_file)
            csv_rows = len(df_csv) - 1
            # Count files with specific extensions
            image_count = sum(
                1 for file in os.listdir(output_path)
                if os.path.isfile(os.path.join(output_path, file)) and file.lower().endswith(('.tif', '.jpg', '.jpeg'))
            )"""

            if not pdf_exists:
                print(f"Skipping {folder}: No PDF file found in OUTPUT")

            if pdf_exists and csv_file: # and image_count >= csv_rows:
                valid_folders.append(folder)
            else:
                invalid_folders.append(folder)
        else:
            print(f'no output folder exists for {folder}')
            invalid_folders.append(folder)
            

       
    return valid_folders, invalid_folders

def make_dict(valid_folders, flight_config_dict, sensor_dict, om_folder, regen_shell_scripts = False, date_range = None, location_filter = None):
    count = 0
    flight_dict = {}
    folders_not_matched = []
    folders_multiple = []
    om_remaining = []
    folders_remaining = []

    # Initialize the nested keys in the flight_config_dict in the form of[flight][orthomosaic][date]
    for flight, value in flight_config_dict.items():
        if location_filter and flight != location_filter:
            print(f'skipping {flight} because it is not {location_filter}')
            continue
        if flight not in flight_dict:
            flight_dict[flight]= {}

            for om in value.keys():
                if om not in flight_dict[flight]:
                    flight_dict[flight][om] = {}

    for folder in sorted(valid_folders):
        folder_match = False
        folder_parts = folder.strip('/').split('/')

        for flight, value in flight_config_dict.items():
            if location_filter and flight != location_filter:
                print(f'skipping {flight} because it is not {location_filter}')
                continue
            for om in value.keys():
                # Find the farm and field
                farm_field = flight.split('_')
                farm = farm_field[0]
                if len(farm_field) == 2:
                    field = farm_field[1]
                    if field == 'n':
                        field = '_n_'
                else:
                    field  = None
                    #Find the field
                if farm in folder_parts[8].lower():
                    if field is None or field in folder_parts[9].lower(): 
                        date = folder_parts[8][:8]

                        for sensor_type, sensor_name in sensor_dict.items():
                            if sensor_name in folder_parts[9].lower():
                                if sensor_type not in flight_dict[flight][om]:
                                    flight_dict[flight][om][sensor_type] = {}
                                if date not in flight_dict[flight][om][sensor_type]:
                                    folder_match = True
                                    tif_file = os.path.join(om_folder, f'{om}_{sensor_type}_{date}.tif')
                                    if (date_range and date >= date_range[0] and date <= date_range[1]) or not date_range:  # If date_range is not provided, process all dates
                                        if not os.path.exists(tif_file) or regen_shell_scripts:
                                            print(f'DOES NOT EXIST: {om}_{sensor_type}_{date}.tif')
                                            om_remaining.append(f'{om}_{sensor_type}_{date}.tif')
                                            folders_remaining.append(folder)
                                            count += 1
                                            flight_dict[flight][om][sensor_type][date] = folder
                                        #else:
                                        #    print(f'Orthomosaic for {location}_{sensor_type}_{date} already exists')
                                        # Update dictionary to include each step for a given date to note if it is complete or not. 
                                        # for step in uas_pipeline:
                                        # Check if each output_folder/file exists and mark the step as compleete or incomplete.
                                    # If the date already exists in the dictionary, mark this one as a multiple
                                else:
                                    print(f'folder multiple: {folder}')
                                    folders_multiple.append(folder)
                                    consolidate_images(folder, flight, sensor_type, sensor_name, date)
                                    folder_match = True

        if folder_match == False:
            folders_not_matched.append(folder)                

    print(f'number of geotagged folders remaining to generate orthomosaic: {count}')
    return flight_dict, count, folders_not_matched, folders_multiple, om_remaining, folders_remaining


def get_image_metadata(image_path):
    """
    Extracts latitude, longitude, and date from a geotagged image (.jpg or .tif) using ExifTool.

    Args:
        image_path (str): Path to the image file.

    Returns:
        dict: Dictionary containing latitude, longitude, and date.
    """
    exif_cmd = [
        'exiftool', '-GPSLatitude', '-GPSLongitude', '-DateTimeOriginal', '-json', image_path
    ]

    result = subprocess.run(exif_cmd, capture_output=True, text=True)
    
    try:
        metadata = json.loads(result.stdout)[0]
        lat_dms = metadata.get('GPSLatitude')
        lon_dms = metadata.get('GPSLongitude')

        if lat_dms and lon_dms:
            lat = dms_to_decimal(lat_dms)
            lon = dms_to_decimal(lon_dms)

        return {'latitude': lat, 'longitude': lon}
    except (IndexError, json.JSONDecodeError):
        print(f"⚠ Unable to read EXIF metadata for {image_path}")
        return None
    
def dms_to_decimal(dms_str):
    """
    Converts a GPS coordinate from Degrees, Minutes, Seconds (DMS) format to Decimal Degrees (DD).

    Args:
        dms_str (str): DMS coordinate as a string (e.g., "83 deg 45' 22.89\" W")

    Returns:
        float: Decimal degree representation of the coordinate.
    """
    dms_regex = r"(\d+) deg (\d+)' ([\d.]+)\" ([NSEW])"
    match = re.match(dms_regex, dms_str)

    if match:
        degrees = float(match.group(1))
        minutes = float(match.group(2))
        seconds = float(match.group(3))
        direction = match.group(4)

        decimal = degrees + (minutes / 60.0) + (seconds / 3600.0)

        if direction in ["S", "W"]:  # South and West are negative
            decimal *= -1

        return decimal
    else:
        raise ValueError(f"Invalid DMS format: {dms_str}")
    

def create_omspecific_output_folders(flight_dict, flight_config_dict, rerun_boundary = False):
    for flight, value in flight_dict.items():
        for om, value2 in value.items():
            #print(f'om: {om}')
            if flight_config_dict[flight][om]:
                boundary_file = flight_config_dict[flight][om]
                print(f'boundary file: {boundary_file}')
                for sensor, dates in value2.items():
                    print(f'sensor: {sensor}')
                    for date, folder in dates.items():
                        print(f'date: {date}')
                        if date == '20240816':
                             print(f' waltz flight: {date}')
                        print(f'folder: {folder}')
                        omimage_folder = os.path.join(folder, f'OUTPUT_{om}')
                        if not os.path.exists(omimage_folder) or rerun_boundary:
                            filtered_images = filter_images_by_boundary(om, folder, boundary_file, force_exiftags = False)
                            print(f' Length of filtered_images: {len(filtered_images)}')
                            move_images_to_folder(filtered_images, folder, om)
                            print(f'folder: {folder}')

def filter_images_by_boundary(om, folder, boundary_file, force_exiftags=False):
    #Load all of the images into a dictionary where the key is the image name and the value is the image path
    #Load the boundary into a shapely object
    #Filter the images by the boundary

    boundary = gpd.read_file(boundary_file)
    boundary.to_crs(epsg=4326, inplace=True)
    boundary = boundary.unary_union

    filtered_images = []
    output_folder = folder + 'OUTPUT/'
    omimage_folder = os.path.join(folder, f'OUTPUT_{om}')

    if os.path.exists(omimage_folder):
        # Move images back to OUTPUT folder
        for f in os.listdir(omimage_folder):
            old_path = os.path.join(omimage_folder, f)
            new_path = os.path.join(output_folder, f)
            os.rename(old_path, new_path)
        print(f'Moved {old_path} → {new_path}')

    # if it exists load csv file
    csv_files = glob.glob(os.path.join(output_folder, "*.csv"))

    # check if there is a csv file but it is empty
    if csv_files:
        try:
            df_csv = pd.read_csv(csv_files[0])
            if df_csv.empty:
                print(f'Empty CSV file found: {csv_files[0]}')
                csv_files = []
        except pd.errors.EmptyDataError:
            print(f'CSV file exists but has no data: {csv_files[0]}')
            csv_files = []
        except Exception as e:
            print(f'Error reading CSV file {csv_files[0]}: {str(e)}')
            csv_files = []

    if force_exiftags or not csv_files:
        for i, f in enumerate(sorted(os.listdir(output_folder))):
            if f.lower().endswith(('.tif', '.jpg', '.JPG', '.jpeg')):
                image_path = os.path.join(output_folder, f)
                #print(f'Processing {f}')
                # get the latitude and longitude values from the image with exiftool
                metadata = get_image_metadata(image_path)
                lat, lon = metadata['latitude'], metadata['longitude']
                #print(f'lat = {lat}, lon = {lon}')
                if lat and lon:
                    point = Point(lon, lat)
                    if boundary.contains(point):
                        filtered_images.append(image_path)
                        if i % 100 == 0:
                            print(f'Image {f} is within the boundary')
                    else:
                        if i % 100 == 0:
                            print(f'Image {f} is outside the boundary')

    elif csv_files:
        # Read all CSV files into a single DataFrame
        df_csv = pd.concat((pd.read_csv(f) for f in csv_files), ignore_index=True)
        for i, f in enumerate(sorted(os.listdir(output_folder))):
            if f.lower().endswith(('.tif', '.jpg', '.JPG', '.jpeg')):
                image_path = os.path.join(output_folder, f)
                # Find the row in the csv file that matches the image name
                row = df_csv.loc[df_csv['# image name'] == f]
                if not row.empty:
                    lat = row['latitude [decimal degrees]'].values[0]
                    lon = row['longitude [decimal degrees]'].values[0]
                    if lat and lon:
                        point = Point(lon, lat)
                        if boundary.contains(point):
                            filtered_images.append(image_path)
                            if i % 100 == 0:
                                print(f'Image {f} is within the boundary')
                        else:
                            if i % 100 == 0:
                                print(f'Image {f} is outside the boundary')
                else:
                    print(f'No metadata found for {f}')
                    # If it cannot be 
                    filtered_images.append(image_path)

    print(f'returned filtered images: {len(filtered_images)}')
    return filtered_images

def move_images_to_folder(images, folder, om):
    # Move images within the specified boundary to a new folder

    output_folder = os.path.join(folder, 'OUTPUT')
    omimage_folder = os.path.join(folder, f'OUTPUT_{om}')

    # Create omimage folder if it doesn't exist
    os.makedirs(omimage_folder, exist_ok=True)

    for i, f in enumerate(os.listdir(output_folder)):
        if f.lower().endswith(('.tif', '.jpg', '.JPG', '.jpeg')):
            full_image_path = os.path.join(output_folder, f)
            if full_image_path in images:
                old_path = os.path.join(output_folder, f)
                new_path = os.path.join(omimage_folder, f)
                os.rename(old_path, new_path)
                if i % 100 == 0:
                    print(f'Moved {old_path} → {new_path}')






def consolidate_images(folder, location, sensor_type, sensor_name, date):
    #Move all images to a single folder
    #Find all folders for the sensor_type and date
    print(f'-------Multiple folders found')
    print(f'location = {location}')
    print(f'sensor_name = {sensor_name}')
    print(f'date = {date}')

    # Go up to the parent folder
    parent_folder = Path(folder).parents[2]
    print(f'parent_path: {parent_folder}')  # Output: /home/user

    # Find all folders for the sensor_type case insensitive
    sensor_folders = sorted([f for f in os.listdir(parent_folder) if sensor_name in f.lower()])

    print(f'sensor_folders = {sensor_folders}')

    image_folders = []
    for sensor_folder in sensor_folders:
        image_folder = os.path.join(parent_folder, sensor_folder,'01_Images', sensor_folder, 'OUTPUT')
        image_folders.append(image_folder)
    #print(f'image_folders = {image_folders}')

    # Move all images to first folder and prepend with folder number
    for i, image_folder in enumerate(image_folders):
        if i > 0:
            print(f'Processing {image_folder}')
            for file in os.listdir(image_folder):
                if file.lower().endswith(('.tif', '.jpg', '.jpeg')):
                    os.rename(os.path.join(image_folder, file), os.path.join(image_folders[0], f"{i+1}_{file}"))
                    #print(f'Moving {file} to {image_folders[0]}')
                if file.lower().endswith('.csv'):
                    # Prepend image names with folder number
                    geotag_csv = pd.read_csv(os.path.join(image_folder, file))
                    geotag_csv['# image name'] = geotag_csv['# image name'].apply(lambda x: f"{i+1}_{x}")
                    geotag_csv.to_csv(os.path.join(image_folders[0], file), index=False)
                    print(f'moved csv file: {os.path.join(image_folder, file)}')
                    # Prepend image names with folder number

            # Rename the sensor_folder to keep from future runs trying to move images again, include sensor_type but not sensor_name so it is not found again.
            
            new_folder_name = os.path.join(Path(image_folder).parents[1],f'{i+1}_{date}_{location}_{sensor_type}_consolidated')
            os.rename(Path(image_folder).parents[0], new_folder_name)
            
            new_folder_name = os.path.join(Path(image_folder).parents[3],f'{i+1}_{date}_{location}_{sensor_type}_consolidated')
            os.rename(Path(image_folder).parents[2], new_folder_name)



            print(f'Renamed {image_folder} to {new_folder_name}')


def check_output_in_folders(folders):
    """
    Create a list indicating if 'OUTPUT' exists in each folder.

    :param folders: List of folder paths to check.
    :return: List of booleans indicating presence of 'OUTPUT' in each folder.
    """
    output_exists = []
    for folder in folders:
        output_path = os.path.join(folder, 'OUTPUT')
        # Check if 'OUTPUT' folder exists
        if os.path.isdir(output_path):
            # Check if there's any .pdf file in the 'OUTPUT' folder
            pdf_exists = any(file.lower().endswith('.pdf') for file in os.listdir(output_path) if os.path.isfile(os.path.join(output_path, file)))
            output_exists.append(pdf_exists)
        else:
            output_exists.append(False)
    return output_exists

def separate_folders_by_output(folders, output_flags):
    """
    Separate folders into two lists based on whether 'OUTPUT' exists.

    :param folders: List of folder paths.
    :param output_flags: List of booleans indicating presence of 'OUTPUT' in each folder.
    :return: Two lists - folders with 'OUTPUT' and folders without 'OUTPUT'.
    """
    folders_output = [folder for folder, exists in zip(folders, output_flags) if exists]
    folders_nooutput = [folder for folder, exists in zip(folders, output_flags) if not exists]
    return folders_output, folders_nooutput

def count_files_in_output(folders_output):
    """
    Count the number of files in each 'OUTPUT' folder.

    :param folders_output: List of folder paths that contain 'OUTPUT'.
    :return: A list of tuples with the folder path and the number of files in its 'OUTPUT' folder.
    """
    output_file_counts = []
    for folder in folders_output:
        output_path = os.path.join(folder, 'OUTPUT')
        if os.path.isdir(output_path):
            # Count only .tif or .jpg files, case-insensitive
            num_files = sum([
                1 for item in os.listdir(output_path)
                if os.path.isfile(os.path.join(output_path, item)) and
                item.lower().endswith(('.tif', '.jpg'))
            ])
            output_file_counts.append((output_path, num_files))
    return output_file_counts

def sort_folders_by_date(folders):
    """
    Sort folders by date based on the first 8 characters (assuming format yyyymmdd).

    :param folders: List of folder paths to sort.
    :return: Sorted list of folder paths.
    """
    # Define a function to extract the date part from the folder path
    def extract_date(folder):
        path_parts = folder.split('/')
        # Ensure path_parts[9] or equivalent exists before slicing to avoid errors
        if len(path_parts) > 9:
            return path_parts[6][:8]  # Adjust the index if needed based on folder structure
        return ''  # Return an empty string if the date part doesn't exist

    # Sort the folders based on the extracted date
    return sorted(folders, key=extract_date)

def write_folders_to_csv(file_path, folder_list):
    """
    Write a list of folder paths to a CSV file.

    :param file_path: The path to the output CSV file.
    :param folder_list: The list of folder paths to write.
    """

    folder_shortpath = []
    for folder, count in folder_list:
        path_parts = folder.split('/')
        #print(path_parts[9])
        short_path = path_parts[6] + '/' + path_parts[7]
        folder_shortpath.append((short_path, count))
    try:
        with open(file_path, mode='w', newline='') as file:
            writer = csv.writer(file)
            writer.writerow(['Folder Path'])  # Write header
            for short_path, count in folder_shortpath:
                writer.writerow([short_path, count])
        print(f"CSV file written successfully at {file_path}")
    except Exception as e:
        print(f"An error occurred while writing to {file_path}: {e}")




if __name__ == "__main__":

# Example usage
    #path_to_list = '/Users/lukewaltz/Library/CloudStorage/OneDrive-TheOhioStateUniversity/ResearchProjects/20240501-uas/flights/'
    path_to_list = '/fs/ess/PAS2699/uas_data/flights/'
    print(f'path listing: {path_to_list}')
    folders = list_folders_two_levels_deep(path_to_list)

    # Check if 'OUTPUT' exists inside each path in the folders list
    output_flags = check_output_in_folders(folders)

    # Separate folders into two lists based on the presence of 'OUTPUT'
    folders_output, folders_nooutput = separate_folders_by_output(folders, output_flags)

    # Sort folders_nooutput by date
    folders_nooutput_sorted = sort_folders_by_date(folders_nooutput)
    folders_output_sorted = sort_folders_by_date(folders_output)

    # Count the number of files in each 'OUTPUT' folder
    output_file_counts = count_files_in_output(folders_output_sorted)

    # Write the sorted lists to separate CSV files
    #write_folders_to_csv(path_to_list + 'notgeotagged.csv', folders_nooutput_sorted)
    #write_folders_to_csv(path_to_list + 'geotagged.csv', folders_output_sorted)

    # Write the sorted lists to separate CSV files
    write_folders_to_csv(path_to_list + 'notgeotagged.csv', [(folder, 0) for folder in folders_nooutput_sorted])  # Use 0 for file count
    write_folders_to_csv(path_to_list + 'geotagged.csv', output_file_counts)