general:
  seed: 42
  device: "cuda"  # or "cpu"
  use_ddp: true
  log_dir: "logs/tensorboard_logs_resnet_transform/"
  model_save_dir: "models/pd_split_resnet_transform/"

training:
  batch_size: 32
  learning_rate: 6.316786762748272e-05
  num_epochs: 100
  patience: 10  # for early stopping
  optimizer: "adamw"  
  weight_decay: 1.1055960209844369e-05
  test: true
  train: false
  num_folds: 2

dataset:
  planting_date_csv: "datasets/planting_dates(2024).csv"
  corn_plot_csv: "datasets/planting_dates(plot_data_corn_2024).csv"
  soy_plot_csv: "datasets/planting_dates(plot_data_soy_2024).csv"
  image_folder: "/fs/ess/PAS2699/nitrogen/data/uas/2024/plot_patches/patches_rgb_om/"
  growth_stage_csvs:
    - "datasets/Corn Stage and Canopeo 2024(Northwest CORN State).csv"
    - "datasets/Corn Stage and Canopeo 2024(Wooster CORN Stage).csv"
    - "datasets/Soy Stage and Canopero 2024(Northwest Soy State).csv"
    - "datasets/Soy Stage and Canopero 2024(Wooster Soy Stage).csv"
    - "datasets/Corn Stage and Canopeo 2024(Western CORN stage).csv"
    - "datasets/Soy Stage and Canopero 2024(Western Soy stage).csv"

model:
  name: "vit_small_r26_s32_224"
  num_classes: 1
